version: '3'
services:
  helpdesk:
    image: emersonrc/helpdesk
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://helpdesk-db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  helpdesk-db:
    image: 'postgres:13.1-alpine'
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    volumes:
    - helpdesk-volume:/var/lib/postgresql/data

volumes:
  helpdesk-volume: